name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone github repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install app dependencies
      run: npm install
    - name: Run integration test
      run: npm run test

  security_test:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Clone github repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
       node-version: 20
       cache: 'npm'
    - name: Install app dependencies
      run: npm install
    - name: Run security tests
      run: npm audit
  
  deploy:
      runs-on: ubuntu-latest
      needs: ['build_test', 'security_test']
      steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
